spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:41852/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=BAkjoEoHZyWPhUQmXREEcSFjpOicArNc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

management.endpoints.web.exposure.include=health,info
